const icons={home:'<svg viewBox="0 0 24 24"><path d="m3 11 9-8 9 8v10h-6v-6H9v6H3z"/></svg>',meetings:'<svg viewBox="0 0 24 24"><path d="M8 2v4M16 2v4M3 9h18M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2z"/></svg>',checkin:'<svg viewBox="0 0 24 24"><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM15 14h2v2h-2zM19 14h1v4h-3v2h-3v-3h2"/></svg>',service:'<svg viewBox="0 0 24 24"><path d="M12 21s-8-4.5-8-11a4.5 4.5 0 0 1 8-2.8A4.5 4.5 0 0 1 20 10c0 6.5-8 11-8 11z"/></svg>',profile:'<svg viewBox="0 0 24 24"><path d="M20 21a8 8 0 0 0-16 0M12 13a5 5 0 1 0 0-10 5 5 0 0 0 0 10z"/></svg>',dashboard:'<svg viewBox="0 0 24 24"><path d="M4 13h6V4H4zM14 20h6v-9h-6zM4 20h6v-3H4zM14 7h6V4h-6z"/></svg>',roles:'<svg viewBox="0 0 24 24"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M19 8v6M16 11h6"/></svg>'};
const memberNav=[['home','首页','home'],['meetings','聚会','meetings'],['checkin','签到','checkin'],['service','我的服事','service'],['profile','我的','profile']];
const adminNav=[['admin-dashboard','总览','dashboard'],['admin-meetings','聚会管理','meetings'],['admin-schedule','服事排班','service'],['admin-roles','角色权限','roles']];
const programCN=[['7:30','宣召','主席：王志明长老'],['7:35','诗歌敬拜','敬拜团队'],['7:55','欢迎与家事分享','主席'],['8:05','奉献','招待团队'],['8:10','读经','罗马书 12:9–13'],['8:15','证道：在盼望中等候','陈国恩牧师'],['8:55','回应诗歌','敬拜团队'],['9:05','祝祷','陈国恩牧师']];
const programEN=[['7:30','Call to Worship','Service Leader: Elder Wang'],['7:35','Praise & Worship','Worship Team'],['7:55','Welcome & Announcements','Service Leader'],['8:05','Offering','Welcome Team'],['8:10','Scripture Reading','Romans 12:9–13'],['8:15','Sermon: Waiting in Hope','Rev. Tan Kok En'],['8:55','Response Song','Worship Team'],['9:05','Benediction','Rev. Tan Kok En']];
const teamNotes=['麦克风 1 开启；投影显示宣召页','Key: G；第一首后接祷告，无间奏','翻译员预备；投影切换中英家事','招待由后排向前收奉献袋','讲台灯 80%；英文经文同步','翻译耳机频道 2；录影开始','降 Key 至 F；灯光转暖','全体服事人员留步简短祷告'];
let isAdmin=false, english=false, activeRoute='home';
const views=document.querySelectorAll('.view'),modal=document.getElementById('modalBackdrop'),modalContent=document.getElementById('modalContent'),toast=document.getElementById('toast');
function renderNav(){const data=isAdmin?adminNav:memberNav;const html=data.map(([route,label,icon])=>`<button class="nav-button ${activeRoute===route?'active':''}" data-route="${route}">${icons[icon]}<span>${label}</span></button>`).join('');document.getElementById('desktopNav').innerHTML=html;document.getElementById('mobileNav').innerHTML=html;bindRoutes()}
function route(name){const target=document.querySelector(`[data-view="${name}"]`);if(!target)return;activeRoute=name;views.forEach(v=>v.classList.toggle('active',v===target));renderNav();window.scrollTo(0,0);if(name.includes('meeting'))renderPrograms();document.getElementById('main').focus({preventScroll:true})}
function bindRoutes(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route))}
function renderProgram(target,data,team=false){document.getElementById(target).innerHTML=data.map((x,i)=>`<div class="program-item"><time>${x[0]}</time><strong>${x[1]}</strong><span>${x[2]}</span>${team?`<span class="team-note">服事提示：${teamNotes[i]}</span>`:''}</div>`).join('')}
function renderPrograms(){const satTeam=document.querySelector('#programRole button.active')?.dataset.role==='team';const sunTeam=document.querySelector('.sunday-role button.active')?.dataset.role==='team';renderProgram('saturdayProgram',english?programEN:programCN,satTeam);renderProgram('sundayProgram',programCN,sunTeam)}
function showModal(html){modalContent.innerHTML=html;modal.hidden=false;document.body.style.overflow='hidden';setTimeout(()=>modal.querySelector('input,button:not(.modal-close)')?.focus(),20)}
function closeModal(){modal.hidden=true;document.body.style.overflow='';}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),3000)}
function success(title,body){showModal(`<div class="success-icon">✓</div><h2 id="modalTitle">${title}</h2><p>${body}</p><button class="primary-button full" onclick="document.getElementById('modalClose').click()">完成</button>`)}
document.getElementById('modeSwitch').onclick=()=>{isAdmin=!isAdmin;const copy=document.querySelector('.mode-copy strong');copy.textContent=isAdmin?'管理后台':'会友';document.querySelector('.mode-avatar').textContent=isAdmin?'王':'林';document.querySelector('.side-intro').innerHTML=isAdmin?'<span>管理身份</span><strong>王志明长老</strong><small>Super Admin · 全部范围</small>':'<span>主内平安</span><strong>林恩慈姐妹</strong><small>会友编号 GPC-0186</small>';route(isAdmin?'admin-dashboard':'home')};
document.getElementById('languageToggle').onclick=()=>{english=!english;document.querySelectorAll('#languageToggle span').forEach((s,i)=>s.classList.toggle('active',english?i===1:i===0));const text=english?{satTitle:'Saturday Evening Service',satMeta:'22 August · 7:30 PM · Main Hall',sermonTitle:'Waiting in Hope',sermonVerse:'Romans 12:9–13',speaker:'Speaker',translator:'Mandarin / English',checkin:'Check in for service'}:{satTitle:'星期六晚堂',satMeta:'8月22日 · 晚上 7:30 · 教会大堂',sermonTitle:'在盼望中等候',sermonVerse:'罗马书 12:9–13',speaker:'讲员',translator:'英文翻译',checkin:'参加聚会签到'};Object.entries(text).forEach(([k,v])=>document.querySelector(`[data-i18n="${k}"]`).textContent=v);renderPrograms()};
document.querySelectorAll('#programRole button,.sunday-role button').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPrograms()});
document.getElementById('scanQr').onclick=()=>showModal(`<h2 id="modalTitle">扫描现场 QR</h2><p>请将聚会现场的 QR 放入框内。此原型会模拟扫描成功。</p><div class="scan-demo"><span class="scan-frame"><i></i>QR</span></div><button class="primary-button full" id="simulateScan">模拟扫描成功</button>`);
document.addEventListener('click',e=>{if(e.target.id==='simulateScan')success('签到成功','林恩慈姐妹，您已签到星期六晚堂。愿您今天满有平安。')});
document.getElementById('memberCode').onclick=()=>showModal(`<h2 id="modalTitle">会友签到</h2><p>输入会友编号或已登记的手机号码。</p><form id="memberForm"><input required placeholder="会友编号或手机号码"><select><option>星期六晚堂 · 7:30 PM</option><option>星期日早堂 · 10:00 AM</option></select><button class="primary-button full">确认签到</button></form>`);
document.getElementById('guestCheckin').onclick=()=>showModal(`<h2 id="modalTitle">网页快速签到</h2><p>曾经登记过的新朋友，请输入手机号码。</p><form id="guestForm"><input required inputmode="tel" placeholder="手机号码"><button class="primary-button full">查找我的资料</button></form>`);
document.addEventListener('submit',e=>{if(e.target.id==='memberForm'){e.preventDefault();success('签到成功','已完成星期六晚堂签到。')}if(e.target.id==='guestForm'){e.preventDefault();success('欢迎再次回来','李佳恩，已为您完成签到。如资料有变，可到接待处更新。')}});
document.getElementById('newcomerForm').onsubmit=e=>{e.preventDefault();success('登记完成，欢迎您！',`${new FormData(e.target).get('name')}，您已完成今天的聚会签到。接待同工会在聚会后向您问候。`);e.target.reset()};
document.getElementById('acceptService').onclick=()=>{document.getElementById('assignmentStatus').className='status accepted';document.getElementById('assignmentStatus').textContent='已接受';document.getElementById('pendingCount').textContent='0';document.querySelector('.assignment-actions').innerHTML='<button class="secondary-button" id="changeReply">更改回应</button>';showToast('已接受服事，负责人会收到通知')};
document.getElementById('declineService').onclick=()=>showModal(`<h2 id="modalTitle">无法参与这次服事？</h2><p>负责人会收到通知并重新安排。您可以简单说明原因。</p><form id="declineForm"><select><option>时间冲突</option><option>身体不适</option><option>不在新山</option><option>其他原因</option></select><input placeholder="补充说明（可不填）"><button class="primary-button full">确认无法服事</button></form>`);
document.addEventListener('submit',e=>{if(e.target.id==='declineForm'){e.preventDefault();closeModal();document.getElementById('assignmentStatus').className='status declined';document.getElementById('assignmentStatus').textContent='无法服事';document.getElementById('pendingCount').textContent='0';document.querySelector('.assignment-actions').innerHTML='<button class="secondary-button">已通知负责人</button>';showToast('负责人已收到通知')}});
document.getElementById('publishSchedule').onclick=()=>showModal(`<h2 id="modalTitle">发布服事排班</h2><p>将通知本次新增或有变动的 3 位服事人员。等待回应的人员可以选择接受或无法服事。</p><button class="primary-button full" id="confirmPublish">确认发布并通知</button>`);
document.addEventListener('click',e=>{if(e.target.id==='confirmPublish'){closeModal();showToast('排班已发布，3 位服事人员已收到通知')}});
document.getElementById('notificationButton').onclick=()=>showModal(`<h2 id="modalTitle">通知</h2><div class="simple-list"><div><span class="mini-date">22<small>AUG</small></span><span><strong>服事安排等待回应</strong><small>星期六晚堂 · 招待</small></span></div><div><span class="mini-date">29<small>AUG</small></span><span><strong>家庭团契联合聚会</strong><small>星期六下午 4:00</small></span></div></div>`);
document.getElementById('addMeeting').onclick=()=>showModal(`<h2 id="modalTitle">新增聚会</h2><p>V0.1 原型已验证入口。正式版将在这里设置日期、语言和程序。</p><button class="primary-button full" onclick="document.getElementById('modalClose').click()">知道了</button>`);
document.getElementById('addAdmin').onclick=()=>showModal(`<h2 id="modalTitle">新增后台人员</h2><form id="adminForm"><input required placeholder="姓名"><select><option>Church Admin</option><option>Ministry Leader</option><option>Service Coordinator</option><option>Volunteer</option></select><select><option>全部聚会</option><option>星期六晚堂</option><option>星期日早堂</option></select><select><option>行政</option><option>敬拜事工</option><option>接待事工</option><option>儿童事工</option></select><button class="primary-button full">发送邀请</button></form>`);
document.addEventListener('submit',e=>{if(e.target.id==='adminForm'){e.preventDefault();closeModal();showToast('后台邀请已建立（原型演示）')}});
document.getElementById('modalClose').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal()});
bindRoutes();renderNav();renderPrograms();
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js');
