const icons={home:'<svg viewBox="0 0 24 24"><path d="m3 11 9-8 9 8v10h-6v-6H9v6H3z"/></svg>',meetings:'<svg viewBox="0 0 24 24"><path d="M8 2v4M16 2v4M3 9h18M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2z"/></svg>',checkin:'<svg viewBox="0 0 24 24"><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM15 14h2v2h-2zM19 14h1v4h-3v2h-3v-3h2"/></svg>',service:'<svg viewBox="0 0 24 24"><path d="M12 21s-8-4.5-8-11a4.5 4.5 0 0 1 8-2.8A4.5 4.5 0 0 1 20 10c0 6.5-8 11-8 11z"/></svg>',profile:'<svg viewBox="0 0 24 24"><path d="M20 21a8 8 0 0 0-16 0M12 13a5 5 0 1 0 0-10 5 5 0 0 0 0 10z"/></svg>',dashboard:'<svg viewBox="0 0 24 24"><path d="M4 13h6V4H4zM14 20h6v-9h-6zM4 20h6v-3H4zM14 7h6V4h-6z"/></svg>',roles:'<svg viewBox="0 0 24 24"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M19 8v6M16 11h6"/></svg>',members:'<svg viewBox="0 0 24 24"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2M8.5 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M17 11a3 3 0 1 0 0-6M23 21v-2a4 4 0 0 0-3-3.6"/></svg>'};
const memberNav=[['home','首页','home'],['meetings','聚会','meetings'],['checkin','签到','checkin'],['service','我的服事','service'],['profile','我的','profile']];
const adminNav=[['admin-dashboard','总览','dashboard'],['admin-meetings','聚会管理','meetings'],['admin-members','会友管理','members'],['admin-schedule','服事排班','service'],['admin-roles','角色权限','roles']];
const virtualMembers=[
  {id:'GPC-T001',name:'林恩慈',english:'Grace Lim',phone:'012-000-1001',language:'中文 + English',group:'喜乐小组',ministry:'接待事工',status:'使用中',cardToken:'VC-7F3K-91LM'},
  {id:'GPC-T002',name:'李家豪',english:'Jason Lee',phone:'012-000-1002',language:'中文',group:'恩典小组',ministry:'影音事工',status:'使用中',cardToken:'VC-2Q8N-44RX'},
  {id:'GPC-T003',name:'陈慧敏',english:'Michelle Tan',phone:'012-000-1003',language:'中文 + English',group:'盼望小组',ministry:'儿童事工',status:'使用中',cardToken:'VC-5M2P-83KD'},
  {id:'GPC-T004',name:'黄志强',english:'Andrew Wong',phone:'012-000-1004',language:'中文',group:'信实小组',ministry:'招待事工',status:'使用中',cardToken:'VC-9R4H-26TW'},
  {id:'GPC-T005',name:'刘美玲',english:'Mary Low',phone:'012-000-1005',language:'中文',group:'喜乐小组',ministry:'敬拜事工',status:'使用中',cardToken:'VC-3B7Y-65QN'},
  {id:'GPC-T006',name:'张国安',english:'Samuel Chong',phone:'012-000-1006',language:'中文 + English',group:'恩典小组',ministry:'音响事工',status:'使用中',cardToken:'VC-8J1C-72PF'},
  {id:'GPC-T007',name:'王乐恩',english:'Joy Ong',phone:'012-000-1007',language:'English + 中文',group:'青年小组',ministry:'敬拜事工',status:'使用中',cardToken:'VC-4N9A-38UX'},
  {id:'GPC-T008',name:'吴佳宁',english:'Hannah Goh',phone:'012-000-1008',language:'中文',group:'盼望小组',ministry:'暂无服事',status:'待跟进',cardToken:'VC-6W2E-57GS'}
];
const checkinServices={
  'SAT-20260822':{name:'星期六晚堂',meta:'2026年8月22日 · 晚上 7:30',english:'Saturday Evening Service'},
  'SUN-20260823':{name:'星期日早堂',meta:'2026年8月23日 · 上午 10:00',english:'Sunday Morning Service'}
};
const programCN=[['7:30','宣召','主席：王志明长老'],['7:35','诗歌敬拜','敬拜团队'],['7:55','欢迎与家事分享','主席'],['8:05','奉献','招待团队'],['8:10','读经','罗马书 12:9–13'],['8:15','证道：在盼望中等候','陈国恩牧师'],['8:55','回应诗歌','敬拜团队'],['9:05','祝祷','陈国恩牧师']];
const programEN=[['7:30','Call to Worship','Service Leader: Elder Wang'],['7:35','Praise & Worship','Worship Team'],['7:55','Welcome & Announcements','Service Leader'],['8:05','Offering','Welcome Team'],['8:10','Scripture Reading','Romans 12:9–13'],['8:15','Sermon: Waiting in Hope','Rev. Tan Kok En'],['8:55','Response Song','Worship Team'],['9:05','Benediction','Rev. Tan Kok En']];
const teamNotes=['麦克风 1 开启；投影显示宣召页','Key: G；第一首后接祷告，无间奏','翻译员预备；投影切换中英家事','招待由后排向前收奉献袋','讲台灯 80%；英文经文同步','翻译耳机频道 2；录影开始','降 Key 至 F；灯光转暖','全体服事人员留步简短祷告'];
const rememberedMemberKey='gpcRememberedMemberV1';
let isAdmin=false, english=false, activeRoute='home', sessionMemberId='';
const views=document.querySelectorAll('.view'),modal=document.getElementById('modalBackdrop'),modalContent=document.getElementById('modalContent'),toast=document.getElementById('toast');
function renderNav(){const data=isAdmin?adminNav:memberNav;const html=data.map(([route,label,icon])=>`<button class="nav-button ${activeRoute===route?'active':''}" data-route="${route}">${icons[icon]}<span>${label}</span></button>`).join('');document.getElementById('desktopNav').innerHTML=html;document.getElementById('mobileNav').innerHTML=html;bindRoutes()}
function route(name){const target=document.querySelector(`[data-view="${name}"]`);if(!target)return;activeRoute=name;views.forEach(v=>v.classList.toggle('active',v===target));renderNav();window.scrollTo(0,0);if(name.includes('meeting'))renderPrograms();if(name==='admin-members')renderMembers();if(name==='admin-member-cards')renderMemberCards();if(name==='checkin')renderCheckinIdentity();document.getElementById('main').focus({preventScroll:true})}
function bindRoutes(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route))}
function renderProgram(target,data,team=false){document.getElementById(target).innerHTML=data.map((x,i)=>`<div class="program-item"><time>${x[0]}</time><strong>${x[1]}</strong><span>${x[2]}</span>${team?`<span class="team-note">服事提示：${teamNotes[i]}</span>`:''}</div>`).join('')}
function renderPrograms(){const satTeam=document.querySelector('#programRole button.active')?.dataset.role==='team';const sunTeam=document.querySelector('.sunday-role button.active')?.dataset.role==='team';renderProgram('saturdayProgram',english?programEN:programCN,satTeam);renderProgram('sundayProgram',programCN,sunTeam)}
function showModal(html){modalContent.innerHTML=html;modal.hidden=false;document.body.style.overflow='hidden';setTimeout(()=>modal.querySelector('input,button:not(.modal-close)')?.focus(),20)}
function closeModal(){modal.hidden=true;document.body.style.overflow='';}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),3000)}
function success(title,body){showModal(`<div class="success-icon">✓</div><h2 id="modalTitle">${title}</h2><p>${body}</p><button class="primary-button full" onclick="document.getElementById('modalClose').click()">完成</button>`)}
function renderMembers(query=''){const normalized=query.trim().toLowerCase();const list=virtualMembers.filter(m=>Object.values(m).some(value=>String(value).toLowerCase().includes(normalized)));document.getElementById('memberRows').innerHTML=list.length?list.map(m=>`<button class="member-row" data-member="${m.id}"><span><i>${m.name[0]}</i><b>${m.name}</b><small>${m.english} · ${m.phone}</small></span><span>${m.id}</span><span>${m.group}</span><span>${m.ministry}</span><span class="status ${m.status==='使用中'?'accepted':'pending'}">${m.status}</span><span>查看 →</span></button>`).join(''):'<p class="empty-members">找不到相符的测试会友。</p>'}
function showMember(id){const m=virtualMembers.find(member=>member.id===id);if(!m)return;const remembered=localStorage.getItem(rememberedMemberKey)===m.id;showModal(`<span class="tag gold">虚拟测试资料</span><h2 id="modalTitle">${m.name} · ${m.english}</h2><dl class="member-detail"><div><dt>会友编号</dt><dd>${m.id}</dd></div><div><dt>测试电话</dt><dd>${m.phone}</dd></div><div><dt>联系语言</dt><dd>${m.language}</dd></div><div><dt>小组</dt><dd>${m.group}</dd></div><div><dt>服事</dt><dd>${m.ministry}</dd></div><div><dt>本机记住状态</dt><dd>${remembered?'已记住':'没有绑定'}</dd></div></dl><div class="modal-actions"><button class="primary-button full" data-member-checkin="${m.id}">使用此人测试签到</button><button class="secondary-button full" data-show-member-card="${m.id}">查看个人 QR 卡</button><button class="secondary-button full" data-revoke-device="${m.id}" ${remembered?'':'disabled'}>取消已记住设备</button></div>`)}
function rememberedMember(){const id=sessionMemberId||localStorage.getItem(rememberedMemberKey);return virtualMembers.find(member=>member.id===id)}
function cardMember(){const token=new URLSearchParams(location.search).get('card');return virtualMembers.find(member=>member.cardToken===token)}
function renderCheckinIdentity(){const member=cardMember()||rememberedMember();const card=document.getElementById('scanQr'),forget=document.getElementById('forgetDevice');if(member){card.innerHTML=`<span class="remembered-avatar">${member.name[0]}</span><span><small>${cardMember()?'已扫描个人 QR 卡':'这部手机已记住您'}</small><strong>欢迎回来，${member.name}</strong><span>按这里确认今天签到</span></span><b>→</b>`;forget.hidden=Boolean(cardMember())}else{card.innerHTML=`<span class="scan-frame"><i></i>${icons.profile}</span><span><small>第一次使用这部手机</small><strong>确认会友身份</strong><span>用已登记手机号码查找资料</span></span><b>→</b>`;forget.hidden=true}}
function showBindMember(){const kiosk=new URLSearchParams(location.search).get('kiosk')==='1';showModal(`<span class="tag gold">第一次使用</span><h2 id="modalTitle">确认您的会友身份</h2><p>输入教会已登记的测试手机号码。正式版会再发送一次性验证码。</p><form id="bindMemberForm"><input name="phone" required inputmode="tel" placeholder="例如：012-000-1001">${kiosk?'':`<label class="remember-device"><input type="checkbox" name="remember"> <span><strong>记住这部私人手机</strong><small>公用手机请勿勾选</small></span></label>`}<button class="primary-button full">查找我的资料</button></form>`)}
function renderMemberCards(){document.getElementById('memberCardGrid').innerHTML=virtualMembers.map(m=>`<article class="print-member-card"><div class="print-member-brand"><span class="brand-mark" aria-hidden="true"><span></span></span><span><strong>长老会新山宣道教会</strong><small>Gereja Presbyterian Clarion</small></span></div><div class="print-member-body"><div><span class="section-kicker">会友签到卡 · 测试</span><h2>${m.name}</h2><p>${m.english}</p><code>${m.id}</code></div><img src="member-${m.id.toLowerCase()}.png" alt="${m.name}个人签到二维码"></div><small>请在教会入口出示此卡 · 卡内不含电话或地址</small></article>`).join('')}
function showMemberCard(id){const m=virtualMembers.find(member=>member.id===id);if(!m)return;showModal(`<span class="tag gold">个人 QR 会友卡</span><div class="member-card-modal"><img src="member-${m.id.toLowerCase()}.png" alt="${m.name}个人签到二维码"><h2 id="modalTitle">${m.name}</h2><p>${m.english} · ${m.id}</p><small>接待人员扫描此卡即可识别测试会友。</small></div><button class="primary-button full" data-route="admin-member-cards">查看全部会友卡</button>`);bindRoutes()}
function selectedService(){const code=new URLSearchParams(location.search).get('checkin');return checkinServices[code]||checkinServices['SAT-20260822']}
function activateCheckinContext(){const code=new URLSearchParams(location.search).get('checkin');const service=checkinServices[code];const member=cardMember();if(!service&&!member)return false;const banner=document.getElementById('checkinContext');banner.hidden=false;if(service)banner.innerHTML=`<span>已扫描现场 QR</span><strong>${service.name}</strong><small>${service.english} · ${service.meta}</small>`;else banner.innerHTML=`<span>已扫描个人 QR 会友卡</span><strong>${member.name} · ${member.id}</strong><small>请选择下方按钮完成${selectedService().name}签到</small>`;route('checkin');return true}
document.getElementById('modeSwitch').onclick=()=>{isAdmin=!isAdmin;const copy=document.querySelector('.mode-copy strong');copy.textContent=isAdmin?'管理后台':'会友';document.querySelector('.mode-avatar').textContent=isAdmin?'王':'林';document.querySelector('.side-intro').innerHTML=isAdmin?'<span>管理身份</span><strong>王志明长老</strong><small>Super Admin · 全部范围</small>':'<span>虚拟测试账号</span><strong>林恩慈姐妹</strong><small>会友编号 GPC-T001</small>';route(isAdmin?'admin-dashboard':'home')};
document.getElementById('languageToggle').onclick=()=>{english=!english;document.querySelectorAll('#languageToggle span').forEach((s,i)=>s.classList.toggle('active',english?i===1:i===0));const text=english?{satTitle:'Saturday Evening Service',satMeta:'22 August · 7:30 PM · Main Hall',sermonTitle:'Waiting in Hope',sermonVerse:'Romans 12:9–13',speaker:'Speaker',translator:'Mandarin / English',checkin:'Check in for service'}:{satTitle:'星期六晚堂',satMeta:'8月22日 · 晚上 7:30 · 教会大堂',sermonTitle:'在盼望中等候',sermonVerse:'罗马书 12:9–13',speaker:'讲员',translator:'英文翻译',checkin:'参加聚会签到'};Object.entries(text).forEach(([k,v])=>document.querySelector(`[data-i18n="${k}"]`).textContent=v);renderPrograms()};
document.querySelectorAll('#programRole button,.sunday-role button').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPrograms()});
document.getElementById('scanQr').onclick=()=>{const member=cardMember()||rememberedMember();if(!member){showBindMember();return}const service=selectedService();success('签到成功',`${member.name}，您已签到${service.name}。愿您今天满有平安。`)};
document.getElementById('memberCode').onclick=showBindMember;
document.getElementById('forgetDevice').onclick=()=>showModal(`<h2 id="modalTitle">清除这部手机的身份？</h2><p>清除后，这部手机下次签到需要重新输入手机号码。会友资料和过去签到记录不会删除。</p><button class="primary-button full" id="confirmForgetDevice">确认清除本机身份</button>`);
document.getElementById('guestCheckin').onclick=()=>showModal(`<h2 id="modalTitle">网页快速签到</h2><p>曾经登记过的新朋友，请输入手机号码。</p><form id="guestForm"><input required inputmode="tel" placeholder="手机号码"><button class="primary-button full">查找我的资料</button></form>`);
document.addEventListener('submit',e=>{if(e.target.id==='bindMemberForm'){e.preventDefault();const data=new FormData(e.target);const phone=String(data.get('phone')).replace(/\D/g,'');const member=virtualMembers.find(m=>m.phone.replace(/\D/g,'')===phone);if(!member){showToast('找不到测试会友，请试用 012-000-1001 至 012-000-1008');return}sessionMemberId=member.id;if(data.get('remember'))localStorage.setItem(rememberedMemberKey,member.id);closeModal();renderCheckinIdentity();showModal(`<div class="success-icon">✓</div><h2 id="modalTitle">已找到 ${member.name}</h2><p>${data.get('remember')?'这部私人手机已记住您的测试身份。':'本次已确认身份，但不会记住这部手机。'}</p><button class="primary-button full" id="finishBoundCheckin">确认${selectedService().name}签到</button>`)}if(e.target.id==='guestForm'){e.preventDefault();success('欢迎再次回来','李佳恩，已为您完成签到。如资料有变，可到接待处更新。')}});
document.getElementById('newcomerForm').onsubmit=e=>{e.preventDefault();success('登记完成，欢迎您！',`${new FormData(e.target).get('name')}，您已完成今天的聚会签到。接待同工会在聚会后向您问候。`);e.target.reset()};
document.getElementById('acceptService').onclick=()=>{document.getElementById('assignmentStatus').className='status accepted';document.getElementById('assignmentStatus').textContent='已接受';document.getElementById('pendingCount').textContent='0';document.querySelector('.assignment-actions').innerHTML='<button class="secondary-button" id="changeReply">更改回应</button>';showToast('已接受服事，负责人会收到通知')};
document.getElementById('declineService').onclick=()=>showModal(`<h2 id="modalTitle">无法参与这次服事？</h2><p>负责人会收到通知并重新安排。您可以简单说明原因。</p><form id="declineForm"><select><option>时间冲突</option><option>身体不适</option><option>不在新山</option><option>其他原因</option></select><input placeholder="补充说明（可不填）"><button class="primary-button full">确认无法服事</button></form>`);
document.addEventListener('submit',e=>{if(e.target.id==='declineForm'){e.preventDefault();closeModal();document.getElementById('assignmentStatus').className='status declined';document.getElementById('assignmentStatus').textContent='无法服事';document.getElementById('pendingCount').textContent='0';document.querySelector('.assignment-actions').innerHTML='<button class="secondary-button">已通知负责人</button>';showToast('负责人已收到通知')}});
document.getElementById('publishSchedule').onclick=()=>showModal(`<h2 id="modalTitle">发布服事排班</h2><p>将通知本次新增或有变动的 3 位服事人员。等待回应的人员可以选择接受或无法服事。</p><button class="primary-button full" id="confirmPublish">确认发布并通知</button>`);
document.addEventListener('click',e=>{if(e.target.id==='confirmPublish'){closeModal();showToast('排班已发布，3 位服事人员已收到通知')}});
document.getElementById('notificationButton').onclick=()=>showModal(`<h2 id="modalTitle">通知</h2><div class="simple-list"><div><span class="mini-date">22<small>AUG</small></span><span><strong>服事安排等待回应</strong><small>星期六晚堂 · 招待</small></span></div><div><span class="mini-date">29<small>AUG</small></span><span><strong>家庭团契联合聚会</strong><small>星期六下午 4:00</small></span></div></div>`);
document.getElementById('addMeeting').onclick=()=>showModal(`<h2 id="modalTitle">新增聚会</h2><p>V0.1 原型已验证入口。正式版将在这里设置日期、语言和程序。</p><button class="primary-button full" onclick="document.getElementById('modalClose').click()">知道了</button>`);
document.getElementById('addAdmin').onclick=()=>showModal(`<h2 id="modalTitle">新增后台人员</h2><form id="adminForm"><input required placeholder="姓名"><select><option>Church Admin</option><option>Ministry Leader</option><option>Service Coordinator</option><option>Volunteer</option></select><select><option>全部聚会</option><option>星期六晚堂</option><option>星期日早堂</option></select><select><option>行政</option><option>敬拜事工</option><option>接待事工</option><option>儿童事工</option></select><button class="primary-button full">发送邀请</button></form>`);
document.addEventListener('submit',e=>{if(e.target.id==='adminForm'){e.preventDefault();closeModal();showToast('后台邀请已建立（原型演示）')}});
document.getElementById('addMember').onclick=()=>showModal(`<span class="tag gold">原型演示</span><h2 id="modalTitle">输入会友资料</h2><p>正式版会在这里保存真实会友。当前原型只演示表单，不会把资料上传到数据库。</p><form id="memberCreateForm"><input required placeholder="中文姓名"><input placeholder="英文姓名"><input required inputmode="tel" placeholder="手机号码"><select><option>中文</option><option>English</option><option>中文 + English</option></select><button class="primary-button full">演示保存</button></form>`);
document.addEventListener('submit',e=>{if(e.target.id==='memberCreateForm'){e.preventDefault();closeModal();showToast('原型演示完成；真实保存需连接数据库')}});
document.getElementById('memberSearch').oninput=e=>renderMembers(e.target.value);
document.getElementById('memberRows').onclick=e=>{const row=e.target.closest('[data-member]');if(row)showMember(row.dataset.member)};
document.addEventListener('click',e=>{const checkin=e.target.closest('[data-member-checkin]');if(checkin){const member=virtualMembers.find(m=>m.id===checkin.dataset.memberCheckin);const service=selectedService();success('签到成功',`${member.name}，您已完成${service.name}测试签到。`)}const card=e.target.closest('[data-show-member-card]');if(card)showMemberCard(card.dataset.showMemberCard);const revoke=e.target.closest('[data-revoke-device]');if(revoke&&!revoke.disabled){if(localStorage.getItem(rememberedMemberKey)===revoke.dataset.revokeDevice)localStorage.removeItem(rememberedMemberKey);sessionMemberId='';closeModal();renderCheckinIdentity();showToast('已取消这部手机的会友身份（原型演示）')}const copy=e.target.closest('.copy-qr');if(copy){navigator.clipboard?.writeText(copy.dataset.url);showToast('签到链接已复制')}if(e.target.id==='confirmForgetDevice'){localStorage.removeItem(rememberedMemberKey);sessionMemberId='';closeModal();renderCheckinIdentity();showToast('这部手机的会友身份已清除')}if(e.target.id==='finishBoundCheckin'){const member=rememberedMember();success('签到成功',`${member.name}，您已完成${selectedService().name}签到。`)}if(e.target.closest('[data-route="admin-member-cards"]')&&modal.contains(e.target))closeModal()});
document.getElementById('printQr').onclick=()=>window.print();
document.getElementById('printMemberCards').onclick=()=>{document.body.classList.add('printing-member-cards');window.print();document.body.classList.remove('printing-member-cards')};
document.getElementById('modalClose').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal()});
bindRoutes();renderNav();renderPrograms();renderMembers();activateCheckinContext();
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js');
